---
title: "Exposure database creation"
author: "Jan Sodoge"
date: "25 7 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
load("~/GitHub/drought-impact-cluster-analysis/data/nuts_geo_layers.RData")
library(tidyverse)
library(sf)
library(readxl)
codes_corine <- read_excel("~/GitHub/drought-impact-cluster-analysis/data/codes_corine.xlsx")

sf_use_s2(FALSE)

nuts3 <- nuts_geo_data %>% 
  dplyr::filter(LEVL_CODE == 3) %>% 
  dplyr::filter(CNTR_CODE == "DE")


nuts2 <- nuts_geo_data %>% 
  dplyr::filter(LEVL_CODE == 2) %>% 
  dplyr::filter(CNTR_CODE == "DE")


nuts3$area_size_total <- sf::st_area(nuts3)



```




## Create data for NUTS-3




```{r}
#load some data: class 1
corine_landcover_1 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class1xx.shp")
corine_landcover_crs_1 <- sf::st_transform(corine_landcover_1, crs = "WGS84")

intersections_sf_1 <- sf::st_intersection(nuts3,
                                        corine_landcover_crs_1)
intersections_sf_codes_1 <- intersections_sf_1 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_1 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts3, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_1.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```



```{r}
#load some data: class 2
corine_landcover_2 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class2xx.shp")
corine_landcover_crs_2 <- sf::st_transform(corine_landcover_2, crs = "WGS84")

intersections_sf_2 <- sf::st_intersection(nuts3,
                                        corine_landcover_crs_2)
intersections_sf_codes_2 <- intersections_sf_2 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_2 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts3, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```




```{r}
#load some data: class 3
corine_landcover_3 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class3xx.shp")
corine_landcover_crs_3 <- sf::st_transform(corine_landcover_3, crs = "WGS84")

intersections_sf_3 <- sf::st_intersection(nuts3,
                                        corine_landcover_crs_3)
intersections_sf_codes_3 <- intersections_sf_3 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_3 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts3, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_3.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```




```{r}
#load some data: class 4
corine_landcover_4 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class4xx.shp")
corine_landcover_crs_4 <- sf::st_transform(corine_landcover_4, crs = "WGS84")

intersections_sf_4 <- sf::st_intersection(nuts3,
                                        corine_landcover_crs_4)
intersections_sf_codes_4 <- intersections_sf_4 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_4 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts3, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_4.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```



```{r}
#load some data: class 5
corine_landcover_5 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class5xx.shp")
corine_landcover_crs_5 <- sf::st_transform(corine_landcover_5, crs = "WGS84")

intersections_sf_5 <- sf::st_intersection(nuts3,
                                        corine_landcover_crs_5)
intersections_sf_codes_5 <- intersections_sf_5 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_5 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts3, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_5.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```





## Create data for NUTS-2



```{r}
#load some data: class 1
corine_landcover_1 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class1xx.shp")
corine_landcover_crs_1 <- sf::st_transform(corine_landcover_1, crs = "WGS84")

intersections_sf_1 <- sf::st_intersection(nuts2,
                                        corine_landcover_crs_1)
intersections_sf_codes_1 <- intersections_sf_1 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_1 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts2, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_1_nuts2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```



```{r}
#load some data: class 2
corine_landcover_2 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class2xx.shp")
corine_landcover_crs_2 <- sf::st_transform(corine_landcover_2, crs = "WGS84")

intersections_sf_2 <- sf::st_intersection(nuts2,
                                        corine_landcover_crs_2)
intersections_sf_codes_2 <- intersections_sf_2 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_2 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts2, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_2_nuts_2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```





```{r}
#load some data: class 3
corine_landcover_3 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class3xx.shp")
corine_landcover_crs_3 <- sf::st_transform(corine_landcover_3, crs = "WGS84")

intersections_sf_3 <- sf::st_intersection(nuts2,
                                        corine_landcover_crs_3)
intersections_sf_codes_3 <- intersections_sf_3 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_3 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts2, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_3_nuts2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```











```{r}
#load some data: class 4
corine_landcover_4 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class4xx.shp")
corine_landcover_crs_4 <- sf::st_transform(corine_landcover_4, crs = "WGS84")

intersections_sf_4 <- sf::st_intersection(nuts2,
                                        corine_landcover_crs_4)
intersections_sf_codes_4 <- intersections_sf_4 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_4 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts2, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_4_nuts2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```



```{r}
#load some data: class 5
corine_landcover_5 <- sf::read_sf("../data/corine_data/clc5_2018.gk3.shape/clc5_2018.gk3.shape/clc5/clc5_class5xx.shp")
corine_landcover_crs_5 <- sf::st_transform(corine_landcover_5, crs = "WGS84")

intersections_sf_5 <- sf::st_intersection(nuts2,
                                        corine_landcover_crs_5)
intersections_sf_codes_5 <- intersections_sf_5 %>%
  dplyr::left_join(codes_corine %>% mutate(code = as.character(code)), by = c("CLC18" = "code"))


intersections_sf_areas <- intersections_sf_codes_5 %>% 
  as_tibble() %>% 
  group_by(description, NUTS_ID) %>% 
  summarise(area_total = sum(Shape_Area, na.rm = TRUE)) %>% 
  dplyr::left_join(nuts2, by = c("NUTS_ID" = "NUTS_ID")) %>% 
  dplyr::select(!geometry) %>% 
  as_tibble()

write.csv(intersections_sf_areas, file = "intersections_sf_areas_5_nuts2.csv")

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
```